[package]
name = "kura_prompt"
version = "0.1.0"
edition = "2021"
authors = ["King of Celephais"]

[dependencies]
git2 = "0.19.0"
lazy_static = "1.5.0"
nu-ansi-term = { version = "0.50.1" }
toml = "0.8.19"
